### PR TITLE
Add idx field to Interface

### PR DESCRIPTION
**Pull request by shinypb**
Knowing the interface index (also known as the interface number) is required for setting some socket options, particularly around IPv6 multicasting (e.g. [UdpSocket#join_multicast_v6](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.join_multicast_v6)).

This adds an idx field on Interface (an `Option<u32>`) and populates it on posix systems. Unfortunately, I am not a Windows programmer, so I'm leaving it unimplemented there; I would be delighted to see someone else pick up the torch and get it implemented on Windows as well.

### CODE REVIEW

**Comment by messense** [comment]
Thanks, there are some build/test failures though.

**Comment by shinypb** [comment]
I see that! Thought `cargo test` had my back  😅I need to spin up some test VMs; I’ll dig in on Monday 💪. On Feb 24, 2023, at 5:21 PM, messense ***@***.***> wrote:﻿
Thanks, there are some build/test failures though.

**Comment by shinypb** [comment]
Hi @messense! I fixed the build errors and added an additional assertion in the test case; please let me know if there's anything  else I can do on this PR. Thanks for your review! :bow:

**Review by messense — APPROVED** [review]

**Comment by messense** [comment]
Published in v0.10.0: https://crates.io/crates/if-addrs/0.10.0

**Pull request merged**
