### PR TITLE
windows-sys 0.52

### PR DESCRIPTION
**Pull request by kayabaNerve**

### CODE REVIEW

**Comment by kayabaNerve** [comment]
Hm. Seems like this is a MSRV bump to at least 1.56 (edition = 2021). Would that be accepted?

**Comment by messense** [comment]
Sure, let's also use edition 2021 for this crate.

**Comment by kayabaNerve** [comment]
CI now passes :)

Also, for documentation purposes, I'd like to link to https://github.com/microsoft/windows-rs/pull/2620.

**Comment by messense** [comment]
Thanks! Will publish a new version when I'm back home from work.

**Pull request merged**
